### ISSUE TITLE
ROBOTC Drivers

### ISSUE THREAD

**Issue by botbench** [Thunderbots-5604/Robot-API#1]
Hey guys and gals,

I saw you put a copy of my drivers in your API.  Make sure you get the one from https://github.com/botbench/robotcdriversuite, otherwise you're going to run into lots of issues with ROBOTC 4.x :)

If you have questions or feedback about my the drivers, let me know!

= Xander

**Comment by ZachOhara** [comment]
Is the 4.x version of the suite backwards compatible? I think most of our code doesn't work with 4.x anyway.

**Comment by botbench** [comment]
I did not check the code for backwards compatibility, no. Make sure you
check the FTC rules to ensure you're not going to have issues with minimum
versions of ROBOTC.
If you're using ROBOTC 3.X, you're probably better off using the older
driver suite repo, it's unmaintained code, though :)

= Xander

**Comment by ZachOhara** [comment]
At least for now, FTC allows both RobotC 3.x and 4.x. When we finally migrate to 4.x, I'll make sure to update the driver system. Thanks for the advice!
